# fly.toml app configuration file generated for trainee-7-23t3 on 2023-12-09T15:28:53+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trainee-7-23t3"
primary_region = "syd"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
